# EasyPlaytime Konfiguration
# Hier kannst du einstellen, welche Zeiteinheiten angezeigt werden sollen

# Zeitformat Einstellungen
format:
  # Zeige Tage (d) - z.B. "5d"
  show-days: true
  
  # Zeige Stunden (h) - z.B. "3h"
  show-hours: true
  
  # Zeige Minuten (m) - z.B. "25m"
  show-minutes: true
  
  # Zeige Sekunden (s) - z.B. "42s"
  show-seconds: true

# Beispiele f端r verschiedene Formate:
# Alle aktiviert: "1d 2h 5m 4s"
# Ohne Sekunden: "1d 2h 5m" (show-seconds: false)
# Nur Stunden und Minuten: "2h 5m" (show-days: false, show-seconds: false)
# Nur Tage und Stunden: "1d 2h" (show-minutes: false, show-seconds: false)

# Nachrichten (optional f端r zuk端nftige Erweiterungen)
messages:
  no-permission: "&cDu hast keine Berechtigung f端r diesen Befehl."
  player-not-found: "&cSpieler '{player}' wurde nicht gefunden."
  config-reloaded: "&aKonfiguration wurde neu geladen!"
