# EasyPlaytime Konfiguration

# Zeitformat Einstellungen
format:
  # Zeige Tage (d) - z.B. "5d"
  show-days: true

  # Zeige Stunden (h) - z.B. "3h"
  show-hours: true

  # Zeige Minuten (m) - z.B. "25m"
  show-minutes: true

# Datenbank-Konfiguration für serverübergreifende Spielzeit-Synchronisation
database:
  # Aktiviere die Datenbank (true für Datenbank, false für lokale YAML-Datei)
  enabled: true

  # Datenbank-Host (z.B. localhost oder deine Datenbank-IP)
  host: "192.168.178.172"

  # Datenbank-Port (Standard: 3306 für MySQL/MariaDB)
  port: 3306

  # Datenbank-Name
  database: "Playtime"

  # Benutzername für die Datenbankverbindung
  username: "thelion"

  # Passwort für die Datenbankverbindung (WICHTIG: Verwende sichere Passwörter und speichere sie nicht in der config.yml!)
  password: "Bunker-2009"

  # Tabelle für Spielzeit-Daten (wird automatisch erstellt)
  table: "player_playtime"

  # Maximale Verbindungszeit (in Sekunden) - Optional
  connection-timeout: 30

# Redis-Konfiguration für schnellere Performance (alternativ zur SQL-Datenbank)
redis:
  # Aktiviere Redis (true für Redis, false für SQL-Datenbank)
  # Hinweis: Redis ist schneller, aber Daten können verloren gehen bei Server-Neustart
  enabled: false

  # Redis-Host (z.B. localhost oder deine Redis-IP)
  host: "localhost"

  # Redis-Port (Standard: 6379)
  port: 6379

  # Redis-Passwort (leer lassen, wenn keins gesetzt)
  password: ""

  # Redis-Datenbank (Standard: 0)
  database: 0
messages:
  no-permission: "&cDu hast keine Berechtigung für diesen Befehl."
  player-not-found: "&cSpieler '{player}' wurde nicht gefunden."
  config-reloaded: "&aKonfiguration wurde neu geladen!"
